### ISSUE TITLE
Show most recently updated plugins

### ISSUE THREAD

**Issue by sumpfralle** [munin-monitoring/munin-plugin-gallery#3]
The landing page could end with a list of most recently updated plugins (probably without pagination). This would let it look a bit more lively (fresh dates are visible for visitors) and it would allow people to stumble upon random plugins.

**Comment by steveschnepp** [comment]
An RSS feed would be awesome ... if we were in the 200x 😉

**Comment by sumpfralle** [comment]
> An RSS feed would be awesome ... if we were in the 200x

indeed :)
In fact: it is already there. I just added a reference to the page heads (c1f24a222e131abf21eff46d904304a71e2ec66e).
